scrape_configs:
  - job_name: 'Snackscription Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Snackscription Review'
      - targets: ['34.124.152.90']
        labels:
          application: 'Snackscription Review (deployed)'